meta_product_name: “Swapzi”

meta_title: “Swapzi – Swap smarter with Swapzi”

meta_description: “The platform that allows people to swap items witth eachother, while having fun and earning rewards”

meta_image: “cover.png” # should exist in `app/assets/images/`

twitter_account: “@product_twitter_account” # required for Twitter Cards
